### ISSUE TITLE
Split generators into generator types?

### ISSUE THREAD

**Issue by mithro** [aolofsson/awesome-hardware-tools#1]
I think it might make sense to group the generators into some categories;

 * Analog generators (BAG / OpenFASoC)
 * FPGA/CRGA generators (OpenFPGA / Fabulous)
 * CPU generators (rocket, vexriscv, etc)
 * Memory generators (openram, lake, DFFRAM, etc)
 * "Other" (???)

Are you okay if we sent a pull request which does this?

**Comment by aolofsson** [comment]
I am not a big fan of buckets and only use them sparingly, design is a spectrum. It's a short enough list for now.
