### ISSUE TITLE
More FPGA tools

### ISSUE THREAD

**Issue by lawrie** [aolofsson/awesome-hardware-tools#21]
You have litex on your list, but not migen the HDL that is uses:

migen A python toolbox for building complex digital hardware

https://github.com/m-labs/migen

You don't seem to have icestudio:

icestudio Visual editor for open FPGA boards

https://github.com/FPGAwars/icestudio

Also possibly:

apio Open source ecosystem for open FPGA boards

https://github.com/FPGAwars/apio

Possibly:

openFPGALoader Universal utility for programming FPGAs

https://github.com/trabucayre/openFPGALoader

I don't know if oss-cad-suite is suitable for this list, but I think it includes open source tools that you have not included:

https://github.com/YosysHQ/oss-cad-suite-build

**Comment by aolofsson** [comment]
Thanks! Adding icestudio and and openfpgaloader
