### ISSUE TITLE
qucs - schematic editor

### ISSUE THREAD

**Issue by mi-and-core** [aolofsson/awesome-hardware-tools#22]
qucs-s may be a candidate for your list ? - Basically it is a schematic editor currently based on qt5   
( https://ra3xdh.github.io/ , https://github.com/ra3xdh/qucs_s)
AppImage for all Linux distributions could be found here: https://download.opensuse.org/repositories/home:/ra3xdh/AppImage/

**Comment by aolofsson** [comment]
Thanks, looks like I had a dead fork 'qucs'
