### ISSUE TITLE
librecell - lctime and lclayout

### ISSUE THREAD

**Issue by themperek** [aolofsson/awesome-hardware-tools#26]
What category this should go in? 

[librecell-layout](https://codeberg.org/librecell/lclayout): Automated layout generator for CMOS standard cells.
[lctime](https://codeberg.org/librecell/lctime): Characterization kit for CMOS cells and tool for handling liberty files.

**Comment by mi-and-core** [comment]
librecell-layout is basically a netlist to layout generator. It should go to category "ASIC" ( "align",  also a netlist to layout generator, is also there.) 
Same with characterization tool lctime.  

BTW: A few open-source semiconductor device modeling tools are missing in the list: 
(a) Charon from Sandia Labs (https://charon.sandia.gov/)
(b) DevSim (https://github.com/devsim/devsim) 
Dockerfiles : https://github.com/thesourcerer8/OpenSourceTCAD

Greetings from "Bad Breisig" to "Bonn"
.

**Comment by aolofsson** [comment]
Great inputs, do you want to do a PR?

**Comment by themperek** [comment]
@aolofsson  Thank you. Sorry for no PR from me. Things are bit hard last days because of submissions before summer holidays.
