### ISSUE TITLE
Add CFU Playground

### ISSUE THREAD

**Issue by ShvetankPrakash** [aolofsson/awesome-hardware-tools#29]
Hi @aolofsson ,

CFU Playground is a full-stack open-source framework for designing lightweight ML accelerators on FPGAs:
https://github.com/google/CFU-Playground/  (Repository)
https://google.github.io/CFU-Playground/     (Additional info)

We'd love to add it to your list. Which category should we use?

**Comment by aolofsson** [comment]
Added
